apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-managed-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: grafana-secret-store
  refreshInterval: 10s

  target:
    name: grafana-operator-auth

  data:
    - secretKey: SERVICE_ACCOUNT_TOKEN
      remoteRef:
        key: grafana-operator-auth-token