longhorn:
  defaultSettings:
    createDefaultDiskLabeledNodes: true

  longhornDriver:
    tolerations:
      - key: "storageNode"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"