longhorn:
  defaultSettings:
    createDefaultDiskLabeledNodes: true

  longhornManager:
    tolerations:
      - key: "storageNode"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  ingress:
    enabled: true
    host: longhorn.robertclarke.co.uk
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls: true
    tlsSecret: longhorn-tls