apiVersion: v2
name: sonobarr
description: A Helm Chart for deploying sonobarr
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 4.6.1
    repository: https://bjw-s-labs.github.io/helm-charts/
