mautrix-discord:
  image:
    registry: dock.mau.dev
    repository: mautrix/discord
    tag: "v0.7.5"

  config:
    bridge:
      permissions:
        "*": relay
        "robertclarke.co.uk": user
        "@robertclarke64:robertclarke.co.uk": admin
      username_template: discord_{{.}}
      displayname_template: '{{if .Webhook}}Webhook{{else}}{{or .GlobalName .Username}}{{if .Bot}} (bot){{end}}{{end}}'
      channel_name_template: '{{if or (eq .Type 3) (eq .Type 4)}}{{.Name}}{{else}}#{{.Name}}{{end}}'
      guild_name_template: '{{.Name}}'
      command_prefix: '!discord'
      management_room_text:
          welcome: "Hello, I'm a Discord bridge bot."
          welcome_connected: "Use `help` for help."
          welcome_unconnected: "Use `help` for help or `login` to log in."
          additional_help: ""

      backfill:
        forward_limits:
          initial:
            dm: 50
            channel: 50
            thread: 50
          missed:
            dm: 50
            channel: 50
            thread: 50

    homeserver:
      address: "https://matrix.robertclarke.co.uk"
      domain: robertclarke.co.uk

    appservice:
      as_token: OsFvRAvHEVTquMsRIOIV7iaxSMeA2M46aflj1e6N3iLns1WuDkR5oahtpx5KYZUE
      hs_token: ic6fFEIJfKLWAHnSFkqDTSSSbn73fs6HzgrH8dAW97uLdTzBIfx2QM1bkbJHZLvz
      database:
        type: sqlite3-fk-wal
        uri: "file:/data/discord.db?_txlock=immediate"
      address: http://matrix-bridges-mautrix-discord.matrix-bridges.svc.cluster.local:29334
      id: discord
      bot:
        username: discordbot
        displayname: "Discord Bot"
        avatar: mxc://maunium.net/nIdEykemnwdisvHbpxflpDlC


  persistence:
    storageClass: unraid-nfs-named

  registration:
    namespaces:
      users:
        - regex: ^@discordbot:robertclarke.co.uk$
          exclusive: true
        - regex: ^@discord_.*:robertclarke.co.uk$
          exclusive: true

