{{- $root := . -}}
{{- range $key, $value := .Values.storageClasses}}
{{ if $value.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: {{ template "nfs-client-provisioner.name" $root }}
    chart: {{ template "nfs-client-provisioner.chart" $root }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
  name: {{ $value.name }}
{{- if $value.defaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: {{ template "nfs-client-provisioner.provisionerName" . }}
allowVolumeExpansion: {{ $value.allowVolumeExpansion }}
reclaimPolicy: {{ $value.reclaimPolicy }}
parameters:
  server: {{ $.Values.nfs.server }}
  share: {{ $.Values.nfs.path }}
{{- if $.Values.nfs.mountOptions }}
volumeBindingMode: Immediate
mountOptions:
  {{- range $.Values.nfs.mountOptions }}
  - {{ . }}
  {{- end }}
{{- end }}
{{ end -}}
{{- end }}
