alloy:
  alloy:
    configMap:
      create: false
    mounts:
      extra:
        - name: containerd-socket
          mountPath: /var/run/containerd/
        - name: containerd-lib
          mountPath: /var/lib/containerd/
          readOnly: true
        - name: rootfs
          mountPath: /rootfs/
          readOnly: true
        - name: sys
          mountPath: /sys/
          readOnly: true
    extraPorts:
      - name: prometheus_receive_http
        port: 9999
        targetPort: 9999

  controller:
    volumes:
      extra:
        - name: containerd-socket
          hostPath: 
            path: /var/run/containerd/
        - name: containerd-lib
          hostPath:
            path: /var/lib/containerd/
        - name: rootfs
          hostPath:
            path: /
        - name: sys
          hostPath:
            path: /sys/

  serviceMonitor:
    enabled: true

  service:
    type: LoadBalancer

custom:
  configMap:
    create: true
    content: |
      {{- .Files.Get "config/config.alloy" | trim }}
    name: alloy
