proxy:
  certClusterIssuer: letsencrypt
  ipAddress: 192.168.1.101
  services:
    - name: lidarr
      host: lidarr.k8s.robertclarke.co.uk
      port: 8686

nfs:
  server: 192.168.1.101
  path: /mnt/user/k8s-pv
  mountOptions:
    - hard
    - nfsvers=4.1

storageClasses:
  - create: true
    name: unraid-nfs
    defaultClass: true
    reclaimPolicy: Retain
    accessModes: ReadWriteOnce
    allowVolumeExpansion: true
    archiveOnDelete: false
    provisionerName: nfs.csi.k8s.io
  - create: true
    name: unraid-nfs-named
    defaultClass: false
    reclaimPolicy: Retain
    accessModes: ReadWriteOnce
    allowVolumeExpansion: true
    archiveOnDelete: false
    provisionerName: nfs.csi.k8s.io
    subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
