httpRoute:
  parentRefs:
    - name: http
      namespace: kgateway-system

proxy:
  certClusterIssuer: letsencrypt
  ipAddress: 192.168.1.101
  services:
    - name: unraid
      host: zima.robertclarke.co.uk
      port: 80
    - name: lidarr
      host: lidarr.robertclarke.co.uk
      port: 8686
    - name: qbittorrent
      host: qbit.robertclarke.co.uk
      port: 8080
    - name: plex
      host: plex.robertclarke.co.uk
      tlsPolicy:
        enabled: true
        caHost: "192-168-1-101.9470edbc31af4c7cad7199ba8e364e82.plex.direct"
        caCertificate: |
          -----BEGIN CERTIFICATE-----
          MIIFPzCCBCegAwIBAgISBQ93fQuF2dTmrs4JaFs7quEpMA0GCSqGSIb3DQEBCwUA
          MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
          EwNSMTMwHhcNMjYwMTIwMTEyOTA2WhcNMjYwNDIwMTEyOTA1WjA5MTcwNQYDVQQD
          DC4qLjk0NzBlZGJjMzFhZjRjN2NhZDcxOTliYThlMzY0ZTgyLnBsZXguZGlyZWN0
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0lSmhHFni3omC98CmNCD
          FDDeRSG5sAdaKQaVOLA26AoNJE6ChoAyE8moKenAjIy60Sz9Tv9fTyR/mkZv1m+T
          XZz+tPsUu4tJlmc0+pFXDxE98v4I+LBPM1cY/apjNVSl8K6aJvLwNn+v/UY/bYee
          BmPcdSmhRKR1naFoiuhT62EX9Qhvszf9xe0wqevQTB5NsY0v0/ZXGWFFE95BtCjd
          4grbQv5iB3bPavyB/doSQJFgttuFjdckyRJZT2I0zyYrv8VRMnY34SOy2j1XB5TV
          9ZP/y+ZmvGffHbSZ6eofDODk5VCW9A8GQfrynG1b6GcILmZIcjnnmDSV/tTPEvNH
          dwIDAQABo4ICRTCCAkEwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUF
          BwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQenwDxNzlAk5tY
          YaoB1cpPfGhT7zAfBgNVHSMEGDAWgBTnq58PLDOgU9NeT3jIsoQOO9aSMzAzBggr
          BgEFBQcBAQQnMCUwIwYIKwYBBQUHMAKGF2h0dHA6Ly9yMTMuaS5sZW5jci5vcmcv
          MDkGA1UdEQQyMDCCLiouOTQ3MGVkYmMzMWFmNGM3Y2FkNzE5OWJhOGUzNjRlODIu
          cGxleC5kaXJlY3QwEwYDVR0gBAwwCjAIBgZngQwBAgEwLgYDVR0fBCcwJTAjoCGg
          H4YdaHR0cDovL3IxMy5jLmxlbmNyLm9yZy80Mi5jcmwwggELBgorBgEEAdZ5AgQC
          BIH8BIH5APcAfQAai51pSleYyJmgyoi99I/AtFZgzMNgDR9x9Gn/x9GsowAAAZvb
          X/WMAAgAAAUAOhUk/wQDAEYwRAIgQICo2g0gvgannsjBmPAMFWTjmUxPoRvzSon1
          /u3rMw4CIDVKYV8WY4YOCs6Hx22IAljL1ZKvYqcLr9ROrYz1l3naAHYASZybad4d
          fOz8Nt7Nh2SmuFuvCoeAGdFVUvvp6ynd+MMAAAGb21/6NAAABAMARzBFAiBVuVEY
          Nkh8d3fYUaknFusuBzK3zGn4Iqv63tX+uFq39wIhAKOds4ZCQ/BG5Oa/bdyJgXjj
          BA/67Xi6LAcJZVDsjob2MA0GCSqGSIb3DQEBCwUAA4IBAQBx2eaAQTMu3sNzyHjI
          hezqvhiRcHnI1WmKpli1Xq4gtnIxR135FLN83wXdKKCOZIH5VupaMoWmypIwsAoa
          R2L1haO6l2Nnt+HiYfvzytUDIfdV4pQO2inPvbT/PrUuDVS45o6F+R8Ac0pzEiJ7
          VjDf/8PYxcP9bD3uzW43/AewHH1hvceHKW5ymuzuUZx0EP8lI47ljtx1fXlkqM6Y
          Se14OOjuvAcBg7Nu6KUMc+uqKWkSdocRNyxp9U6Qbl3hHgvNaLjjQXb/3jWZHm8a
          MP95SYg6Sgri2t+l6V5Wj7UYaJACMIPt6Vx4RMZupmSE3JX5Cv2j3usBlFiGTOr9
          IFul
          -----END CERTIFICATE-----
      port: 32400
    - name: prowlarr
      host: prowlarr.robertclarke.co.uk
      port: 9696
    - name: radarr
      host: radarr.robertclarke.co.uk
      port: 7878
    - name: sonarr
      host: sonarr.robertclarke.co.uk
      port: 8989
    - name: slskd
      host: slskd.robertclarke.co.uk
      port: 5030
    - name: tautulli
      host: tautulli.robertclarke.co.uk
      port: 8181

    # - name: thinkcentre
    #   host: think.robertclarke.co.uk
    #   port: 8006
    #   ipAddress: 192.168.1.135
    #   tlsPolicy:
    #     enabled: true
    #     caHost: thinkcentre.localdomain
    #     caCertificate: |
    #       -----BEGIN CERTIFICATE-----
    #       MIIFEjCCAvqgAwIBAgIBATANBgkqhkiG9w0BAQsFADB2MSQwIgYDVQQDDBtQcm94
    #       bW94IFZpcnR1YWwgRW52aXJvbm1lbnQxLTArBgNVBAsMJDU2NmM2MmRmLTllY2Et
    #       NGFlNC1hODMzLTE0NTI2YzJkNTQ5OTEfMB0GA1UECgwWUFZFIENsdXN0ZXIgTWFu
    #       YWdlciBDQTAeFw0yNTA0MDExNTE4NTVaFw0yNzA0MDExNTE4NTVaMGMxGTAXBgNV
    #       BAsTEFBWRSBDbHVzdGVyIE5vZGUxJDAiBgNVBAoTG1Byb3htb3ggVmlydHVhbCBF
    #       bnZpcm9ubWVudDEgMB4GA1UEAxMXdGhpbmtjZW50cmUubG9jYWxkb21haW4wggEi
    #       MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4UPwBWGNYlEzewBHo0J/piOUy
    #       YsUpsYB9CCgFNzcsBOqPR9MGjg4CeDvmOe7mPzlIV2xIkAU53eExXVwCmSKqISxv
    #       srHjwBaWQU4gvYiSvcXALYPDg92FhWY/qJLvZhU2NH3myiyItkNndHt1DGlNQvLP
    #       E0eaNgS5FjxrHhlMJxS/OfHM1h2atlA3p+MCtdHRBb7SxI98/LNp09h5ZdEjRG29
    #       3u3N1F6YtGy50XXBu8LEEpscXaEVdp3QYt3JcsdDdoPCbWNQHoN1+s4qo1Hk4nzT
    #       2NxzcVhNQtlOk4GdBh+xc5o3440QTNr93tVqfE1lS0I94ETkBP/6xk72tkWBAgMB
    #       AAGjgb0wgbowCQYDVR0TBAIwADATBgNVHSUEDDAKBggrBgEFBQcDATBYBgNVHREE
    #       UTBPhwR/AAABhxAAAAAAAAAAAAAAAAAAAAABgglsb2NhbGhvc3SHBMCoAYeCC3Ro
    #       aW5rY2VudHJlghd0aGlua2NlbnRyZS5sb2NhbGRvbWFpbjAdBgNVHQ4EFgQU5x+C
    #       lf1novYFComXJ3f3ACkndQkwHwYDVR0jBBgwFoAUmCEGaqazxiL/655tTpsEuGjT
    #       K2gwDQYJKoZIhvcNAQELBQADggIBAJH7SsyvKL/IokMZBja6PTo2+A4vcYqOCFaZ
    #       wwOBoDWGvXICPFAC4L4knPzBfBF7RjzXlPrs7Hlfa+vkfMtScNimEXcK4B9bKSby
    #       ajQAlo9rgLM2zMUHP/XLA50cv7qefIkXjPNo8yx8laLDKR9+6MErenYfXv8guhZ9
    #       W9cCFESVjjcpGUr4OpYEGwGhpYNlVmF6aYIfw7vLouLz2r8cIchUMFQl18GED8+S
    #       HaTsLzQTU27g7/wARaC8HYLZBQSOwGBXvuG+uHiwOktO4vcxct3qvmNrhT1ihTTL
    #       aQaaFCld1+yflCGYXlPjMipRuHCd7qoRYqUY3+PvbfDUcykwaCKm+miwdd27uSEy
    #       7vMxR3BTgHZ/FMoeyHv3VOwJJyIP9lGQv0rKxmA0S0En8EGeAZjgYPq9OZcrKnhT
    #       +/1MkEP6vbE0v13PiDKF2T1lkNv1f7m6gACyL/l3C47ZpSg1SbpHOAjQC4Nvq3lq
    #       4UhYt1j0syGVhtiYJ3m7QZ77dUSIttnS3FEEiAu0lC1hsMauqUHiGDgKx8+AZ2GI
    #       FfMF4wDu3wk6S49CftlDuuC/f59cD9syGKlqVPzX31jjmvP/mzvdHrhQm1okW3cg
    #       fIlnrlLZcCURu8v/o68czeGvDqc4TG/yu9A9O0VAwo7m0XIGmQWBjsjKMvnoU2Kh
    #       PiNAJjW7
    #       -----END CERTIFICATE-----

    - name: homeassistant
      host: home.robertclarke.co.uk
      port: 8123
      ipAddress: 192.168.1.49

    - name: amp-games
      host: amp.robertclarke.co.uk
      port: 8080
      ipAddress: 192.168.1.85
    - name: minecraft-bluemap
      host: mc.robertclarke.co.uk
      port: 8100
      ipAddress: 192.168.1.85

nfs:
  server: 192.168.1.101
  path: /mnt/user/k8s-pv
  mountOptions:
    - hard
    - nfsvers=4.1

storageClasses:
  - create: true
    name: unraid-nfs-named
    defaultClass: true
    reclaimPolicy: Retain
    accessModes: ReadWriteOnce
    allowVolumeExpansion: true
    archiveOnDelete: false
    provisionerName: nfs.csi.k8s.io
    subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
