apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    {{- .Values.ipAddressPool.addresses | toYaml | nindent 4 }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    - default

