apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: geopulse-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: geopulse-secrets

  data:
    - secretKey: GEOPULSE_POSTGRES_PASSWORD
      remoteRef:
        key: /geopulse/cnpg-cluster/password
    - secretKey: GEOPULSE_MQTT_PASSWORD
      remoteRef:
        key: /geopulse/GEOPULSE_MQTT_PASSWORD
