apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: push-secret-cnpg
spec:
  resyncInterval: 1m # Remove this field to disable automatic reconciliation of the InfisicalPushSecret CRD.
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  updatePolicy: Replace
  deletionPolicy: None

  destination:
    projectSlug: home-kubernetes-f-zg9
    environmentSlug: prod
    secretsPath: "/geopulse/cnpg-cluster"

  push:
    secret:
      secretName: geopulse-cluster-app
      secretNamespace: {{ .Release.Namespace }}

  authentication:
    kubernetesAuth:
      identityId: 6adb342c-c144-4d35-a576-922b8a6973de
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
