apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: trek

  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: /trek/ENCRYPTION_KEY
