apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonobarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: sonobarr

  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: /sonobarr/SECRET_KEY
    - secretKey: LIDARR_API_KEY
      remoteRef:
        key: /sonobarr/LIDARR_API_KEY
    - secretKey: LAST_FM_API_KEY
      remoteRef:
        key: /sonobarr/LAST_FM_API_KEY
    - secretKey: LAST_FM_API_SECRET
      remoteRef:
        key: /sonobarr/LAST_FM_API_SECRET
