apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wanderer.db.fullname" . }}
  labels:
    {{- include "wanderer.db.labels" . | nindent 4 }}
spec:
  {{- if not .Values.db.autoscaling.enabled }}
  replicas: {{ .Values.db.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wanderer.db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wanderer.db.labels" . | nindent 8 }}
        {{- with .Values.db.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.db.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wanderer.serviceAccountName" . }}
      {{- with .Values.db.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.db.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.db.service.port }}
              protocol: TCP
          {{- with .Values.db.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.db.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.db.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.db.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.global.env .Values.db.env }}
          env:
            {{- with .Values.global.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.db.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.db.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.db.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
