global:
  env: {}

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/seanmorley15/adventurelog-frontend
    pullPolicy: IfNotPresent
    tag: "v0.11.0"

  env:
    - name: PUBLIC_SERVER_URL
      value: "http://adventurelog-backend:80"
    - name: ORIGIN
      value: "https://adventures.robertclarke.co.uk"
    - name: BODY_SIZE_LIMIT
      value: "Infinity"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 3000

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

  # Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}
  tolerations: []
  affinity: {}

backend:
  replicaCount: 1
  image:
    repository: ghcr.io/seanmorley15/adventurelog-backend
    pullPolicy: IfNotPresent
    tag: "v0.11.0"

  env:
    - name: PGHOST
      value: "adventurelog-db"
    - name: PGDATABASE
      value: "database"
    - name: PGUSER
      value: "adventure"
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: adventurelog-secret
          key: adventure-postgres-password
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: adventurelog-secret
          key: adventure-postgres-password
    - name: PUBLIC_URL
      value: "https://adventures-backend.robertclarke.co.uk" # Match the outward port, used for the creation of image urls
    - name: FRONTEND_URL
      value: "https://adventures.robertclarke.co.uk"
    - name: CSRF_TRUSTED_ORIGINS
      value: "https://adventures.robertclarke.co.uk, https://adventures-backend.robertclarke.co.uk, http://adventurelog-backend:80"
    - name: DJANGO_ADMIN_USERNAME
      valueFrom:
        secretKeyRef:
          name: adventurelog-secret
          key: django-admin-username
    - name: DJANGO_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: adventurelog-secret
          key: django-admin-password
    - name: DJANGO_ADMIN_EMAIL
      valueFrom:
        secretKeyRef:
          name: adventurelog-secret
          key: django-admin-email
    - name: GOOGLE_MAPS_API_KEY
      valueFrom:
        secretKeyRef:
          name: adventurelog-secret
          key: google-maps-api-key
    - name: DEBUG
      value: "True"

  startupProbe:
    httpGet:
      path: /
      port: http
    failureThreshold: 30
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  persistentVolume:
    create: true
    name: "adventurelog-backend-pv"
    storageClass: "unraid-nfs-named"
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi

  volumes:
    - name: backend-data-pv
      persistentVolumeClaim:
        claimName: adventurelog-backend-pv

  volumeMounts:
    - name: backend-data-pv
      mountPath: "/code/media"

  nodeSelector: {}
  tolerations: []
  affinity: {}

db:
  replicaCount: 1
  image:
    repository: postgis/postgis
    pullPolicy: IfNotPresent
    tag: "15-3.3"

  env:
    - name: POSTGRES_DB
      value: database
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata/subdir
    - name: POSTGRES_USER
      value: adventure
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: adventurelog-secret
          key: adventure-postgres-password

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 5432

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  persistentVolume:
    create: true
    name: "adventurelog-db-pv"
    storageClass: "unraid-nfs-named"
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi

  volumes:
    - name: db-data-pv
      persistentVolumeClaim:
        claimName: adventurelog-db-pv

  volumeMounts:
    - name: db-data-pv
      mountPath: "/var/lib/postgresql/data"

  nodeSelector: {}
  tolerations: []
  affinity: {}
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""


ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: adventures.robertclarke.co.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: adventurelog-frontend
              port:
                number: 3000
    - host: adventures-backend.robertclarke.co.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: adventurelog-backend
              port:
                number: 80

  tls:
    - hosts:
        - adventures.robertclarke.co.uk
        - adventures-backend.robertclarke.co.uk
      secretName: adventurelog-tls
