{{- range $key, $value := .Values.applications }}
{{- if or $value.enabled (not (hasKey $value "enabled")) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ default "https://github.com/RobertClarke64/k8s-homelab" $value.repoURL }}
    targetRevision: {{ default "HEAD" $value.targetRevision }}
    path: {{ default $key $value.path }}
    {{- with $value.chart }}
    chart: {{ . }}
    {{- end }}
    {{- if or $value.valueFiles $value.valuesObject }}
    helm:
      {{- range $value.valueFiles }}
      valueFiles:
        - {{ . }}
      {{- end }}
      {{- with $value.valuesObject }}
      valuesObject:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $value.namespace | default $key}}
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }}
