{{ range $key, $value := .Values.applications }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: {{ $value.namespace | default $key}}
    name: {{ $value.namespace | default $key}}
    {{- with $value.extraNamespaceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ $value.namespace | default $key}}
{{ end }}
