applications:
  actualbudget: {}
  adventurelog: {}
  alloy: {}
  argocd: {}
  barassistant: {}
  convertx: {}
  firefly-iii: {}
  stirling-pdf: {}
  linkwarden: {}
  metallb:
    namespace: metallb-system
  metrics-server:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.13.0
    valuesObject:
      args:
        - --kubelet-insecure-tls
  ingress-nginx: {}
  grafana: {}
  wanderer: {}
  karakeep: {}
