applications:
  alloy:
    extraNamespaceLabels:
      pod-security.kubernetes.io/enforce: privileged
  argocd:
    extraSyncOptions:
      - ServerSideApply=true
  barassistant: {}
  cert-manager: {}
  cnpg:
    # renovate: datasource=helm
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.27.1
    extraSyncOptions:
      - ServerSideApply=true
  convertx: {}
  csi-driver-nfs:
    # renovate: datasource=helm
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    chart: csi-driver-nfs
    targetRevision: 4.13.1
    namespace: kube-system
  cyberchef: {}
  external-secrets:
    extraSyncOptions:
      - ServerSideApply=true
  geopulse: {}
  immich: {}
  infisical: {}
  journiv: {}
  kgateway:
    namespace: kgateway-system
    extraSyncOptions:
      - ServerSideApply=true
  prometheus:
    extraNamespaceLabels:
      pod-security.kubernetes.io/enforce: privileged
  prometheus-operator:
    # renovate: datasource=helm
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-operator-crds
    targetRevision: 27.0.0
    extraSyncOptions:
      - ServerSideApply=true
  stirling-pdf: {}
  seerr: {}
  sonobarr: {}
  tandoor: {}
  loki: {}
  lubelogger: {}
  matrix: {}
  matrix-bridges: {}
  metallb:
    namespace: metallb-system
    extraNamespaceLabels:
      pod-security.kubernetes.io/enforce: privileged
  metrics-server:
    # renovate: datasource=helm
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.13.0
    valuesObject:
      args:
        - --kubelet-insecure-tls
  monica: {}
  grafana: {}
  wanderer: {}
  karakeep:
    extraNamespaceLabels:
      pod-security.kubernetes.io/enforce: privileged
  zimaboard: {}
