apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: cloudflare-api-key

  data:
    - secretKey: api-key
      remoteRef:
        key: /cert-manager/cloudflare-api-key
