apiVersion: v2
name: grafana
description: A Helm Chart for deploying grafana
type: application
version: 0.1.0
dependencies:
  - name: grafana
    version: 10.1.4
    repository: https://grafana.github.io/helm-charts
  - name: grafana-operator
    version: v5.20.0
    repository: oci://ghcr.io/grafana/helm-charts
