grafana:
  serviceMonitor:
    enabled: true

  route:
    main:
      enabled: true
      parentRefs:
        - name: http
          namespace: kgateway-system
          sectionName: https
      hostnames:
        - grafana.robertclarke.co.uk


  ingress:
    enabled: false
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - grafana.k8s.robertclarke.co.uk
      - grafana.robertclarke.co.uk
    tls:
      - hosts:
          - grafana.robertclarke.co.uk
        secretName: grafana-tls

  persistence:
    enabled: true
    storageClassName: unraid-nfs-named

  initChownData:
    enabled: false

  sidecar:
    dashboards:
      enabled: true
      provider:
        folder: "Kubernetes"

  grafana.ini:
    feature_toggles:
      alertingListViewV2: true
    security:
      allow_embedding: true


dashboards:
  k8s-system-api-server:
    folder: Kubernetes
    url: "https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json"
  k8s-system-coredns:
    folder: Kubernetes
    url: "https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json"
  k8s-views-global:
    folder: Kubernetes
    url: "https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json"
  k8s-views-namespaces:
    folder: Kubernetes
    url: "https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json"
  k8s-views-nodes:
    folder: Kubernetes
    url: "https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json"
  k8s-views-pods:
    folder: Kubernetes
    url: "https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json"
  k8s-persistent-volumes:
    folder: Kubernetes
    url: "https://grafana.com/api/dashboards/11349/revisions/1/download"
