grafana:
  serviceMonitor:
    enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - grafana.k8s.robertclarke.co.uk
      - grafana.robertclarke.co.uk
    tls:
      - hosts:
          - grafana.robertclarke.co.uk
        secretName: grafana-tls

  persistence:
    enabled: true
    storageClassName: unraid-nfs-named

  initChownData:
    enabled: false

  sidecar:
    dashboards:
      enabled: true
      provider:
        folder: "Kubernetes"
