apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: universal-auth-credentials
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: universal-auth-credentials
      secretsScope:
        projectSlug: home-kubernetes-f-zg9
        environmentSlug: prod
        secretsPath: /
        recursive: false
        expandSecretReferences: false