apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-managed-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: rob-test-secret

  data:
    # When referencing a secret within the `secretsPath`, the `key` can just be a secret
    # name.
    - secretKey: cat
      remoteRef:
        key: /test-secrets/cat
    # Properties can be extracted from secrets that are JSON strings.
    - secretKey: dog
      remoteRef:
        key: /test-secrets/dog