apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wanderer-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: wanderer-secrets

  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: /wanderer/MEILI_MASTER_KEY
    - secretKey: POCKETBASE_ENCRYPTION_KEY
      remoteRef:
        key: /wanderer/POCKETBASE_ENCRYPTION_KEY
    - secretKey: POCKETBASE_SMTP_PASSWORD
      remoteRef:
        key: /wanderer/POCKETBASE_SMTP_PASSWORD
