apiVersion: v2
name: matrix
description: A Helm Chart for deploying a matrix stack
type: application
version: 0.1.0
dependencies:
  - name: matrix
    version: 2.9.14
    repository: https://remram44.github.io/matrix-helm
    import-values:
      - child: service
        parent: matrix.service
  - name: cluster
    version: 0.5.0
    repository: https://cloudnative-pg.github.io/charts
  - name: mautrix-discord
    version: 0.2.1
    repository: https://mjohnson9.github.io/helm/
