apiVersion: v2
name: matrix
description: A Helm Chart for deploying a matrix stack
type: application
version: 0.1.0
dependencies:
  - name: matrix
    version: 2.9.14
    repository: https://remram44.github.io/matrix-helm
  - name: cluster
    version: 0.5.0
    repository: https://cloudnative-pg.github.io/charts

