httpRoute:
  parentRefs:
    - name: http
      namespace: kgateway-system
      sectionName: https
      group: gateway.networking.k8s.io
      kind: Gateway

  matrix:
    hostnames:
      - matrix.robertclarke.co.uk
  element:
    hostnames:
      - chat.robertclarke.co.uk

matrix:
  homeserverConfig:
    server_name: "robertclarke.co.uk"
    public_baseurl: "https://matrix.robertclarke.co.uk"
    web_client_location: "https://chat.robertclarke.co.uk"

    enable_registration: true
    enable_registration_without_verification: true
    # registrations_require_3pid:
    #   - email


    email:
      client_base_url: https://chat.robertclarke.co.uk
      notif_from: Matrix <matrix@robertclarke.co.uk>
      smtp_host: robertclarke.co.uk
      smtp_port: 587
      smtp_user: matrix@robertclarke.co.uk
      force_tls: true
      enable_tls: true
      enable_notifs: true
      invite_client_location: https://chat.robertclarke.co.uk

  extraConfig:
    - key: email.smtp_pass
      secret:
        name: matrix-email
        key: emailPassword
    - key: database.args.user
      secret:
        name: matrix-cluster-app
        key: user
    - key: database.args.password
      secret:
        name: matrix-cluster-app
        key: password
    - key: database.args.dbname
      secret:
        name: matrix-cluster-app
        key: dbname
    - key: database.args.host
      secret:
        name: matrix-cluster-app
        key: host

  storage:
    storageClass: unraid-nfs-named

  element:
    config:
      default_server_config:
        m.homeserver:
          base_url: https://matrix.robertclarke.co.uk
          server_name: Matrix

  postgresql:
    enabled: false

cluster:
  cluster:
    instances: 1
    storage:
      storageClass: unraid-nfs-named
