apiVersion: v2
name: lubelogger
description: A Helm Chart for deploying lubelogger
type: application
version: 0.1.0
dependencies:
  - name: lubelogger
    version: 1.4.5
    repository: https://anza-labs.github.io/charts
  - name: cluster
    version: 0.6.0
    repository: https://cloudnative-pg.github.io/charts
