lubelogger:
  persistence:
    data:
      enabled: true
      storageClass: unraid-nfs-named

  secret:
    create: false
    name: lubelogger-email

  config:
    userConfig:
      EnableAuth: false
