lubelogger:
  persistence:
    data:
      enabled: true
      storageClass: unraid-nfs-named

  secret:
    create: false
    name: lubelogger-email

cluster:
  cluster:
    instances: 1
    storage:
      storageClass: unraid-nfs-named
