apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bonds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: bonds

  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: /bonds/JWT_SECRET
