immich:

  persistentVolume:
    create: true
    name: immich
    storageClass: unraid-nfs-named
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 300Gi

  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-server # Line doesn't do anything except persuade renovate to update image tag automatically
            tag: v2.5.6
          env:
            DB_HOSTNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-cluster-superuser
                  key: host
            DB_USERNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-cluster-superuser
                  key: username
            DB_DATABASE_NAME:
              valueFrom:
                secretKeyRef:
                  name: immich-cluster-app
                  key: dbname
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-cluster-superuser
                  key: password

  immich:
    metrics:
      enabled: true
    persistence:
      library:
        existingClaim: immich

  valkey:
    enabled: true
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: unraid-nfs-named

  server:
    route:
      main:
        enabled: true
        parentRefs:
          - name: http
            namespace: kgateway-system
            sectionName: https
            group: gateway.networking.k8s.io
            kind: Gateway
        hostnames:
          - photos.robertclarke.co.uk

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 99

  machine-learning:
    persistence:
      cache:
        type: persistentVolumeClaim
        storageClass: unraid-nfs-named

cluster:
  cluster:
    imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
    instances: 1
    storage:
      storageClass: unraid-nfs-named
      size: 1Gi
    postgresql:
      shared_preload_libraries:
        - "vchord.so"
    initdb:
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
