alloy:
  configMap:
    # -- Create a new ConfigMap for the config file.
    create: true
    # -- Content to assign to the new ConfigMap.  This is passed into `tpl` allowing for templating from values.
    content: |
      {{- .Files.Get "config/config.alloy" | trim }}

    # -- Name of existing ConfigMap to use. Used when create is false.
    name: alloy
    # -- Key in ConfigMap to get config from.
    key: null
