apiVersion: v2
name: dawarich
description: A Helm Chart for deploying dawarich
type: application
version: 0.1.0
dependencies:
  - name: dawarich
    version: 1.0.5
    repository: https://charts.cogitri.dev
  - name: cluster
    version: 0.3.1
    repository: https://cloudnative-pg.github.io/charts
