dawarich:
  dawarich:
    replicaCount: 1
    hosts:
      - "map.robertclarke.co.uk"

  persistence:
    public:
      enabled: true
      storageClass: "unraid-nfs-named"
      size: 10Gi
    watched:
      enabled: true
      storageClass: "unraid-nfs-named"
      size: 10Gi
    storage:
      enabled: true
      storageClass: "unraid-nfs-named"
      size: 5Gi

  postgresql:
    host: dawarich-cluster-rw
    auth:
      existingSecret: dawarich-cluster-superuser
      secretKeys:
        adminPasswordKey: null

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    hosts:
      - host: map.robertclarke.co.uk
        paths:
          - path: /
            pathType: ImplementationSpecific

  redis:
    persistentVolume:
      storageClass: unraid-nfs-named
    replicas: 1

cluster:
  enabled: false
  cluster:
    instances: 1
    storage:
      storageClass: unraid-nfs-named
  type: postgis
