apiVersion: v2
name: infisical
description: A Helm Chart for deploying Infisical
type: application
version: 0.1.0
dependencies:
  - name: infisical-standalone
    version: 1.7.2
    repository: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
  - name: secrets-operator
    version: 0.10.23
    repository: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
  - name: valkey
    version: 0.9.3
    repository: https://valkey.io/valkey-helm/
  - name: cluster
    version: 0.5.0
    repository: https://cloudnative-pg.github.io/charts
