httpRoute:
  enabled: true
  parentRefs:
    - name: http
      namespace: kgateway-system
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - infisical.robertclarke.co.uk

infisical:
  fullnameOverride: ""

infisical-standalone:
  postgresql:
    enabled: false
    useExistingPostgresSecret:
      enabled: true
      existingConnectionStringSecret:
        name: infisical-cluster-app
        key: uri

  redis:
    enabled: false

cluster:
  cluster:
    instances: 1
    storage:
      size: 16Gi
