infisical-standalone:
  ingress:
    hostName: infisical.robertclarke.co.uk
    nginx:
      enabled: false
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - hosts:
          - infisical.robertclarke.co.uk
        secretName: infisical-tls

  postgresql:
    enabled: false
    useExistingPostgresSecret:
      enabled: true
      existingConnectionStringSecret:
        name: infisical-cluster-app
        key: uri

  redis:
    enabled: false

cluster:
  cluster:
    instances: 1
    storage:
      size: 16Gi
