apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dvinyl
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: dvinyl

  data:
    - secretKey: PASSJWT
      remoteRef:
        key: /dvinyl/PASSJWT
    - secretKey: SESSION_SECRET
      remoteRef:
        key: /dvinyl/SESSION_SECRET
    - secretKey: DISCOGS_TOKEN
      remoteRef:
        key: /dvinyl/DISCOGS_TOKEN
    - secretKey: HARDCOVER_API_KEY
      remoteRef:
        key: /dvinyl/HARDCOVER_API_KEY
