{{ range $key, $value := .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: {{ default $value.namespace $key}}
spec:
  project: default
  source:
    repoURL: https://github.com/RobertClarke64/k8s-homelab
    targetRevision: HEAD
    path: {{ default $value.path $key}}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ default $value.namespace $key}}
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}
