{{ range $key, $value := .Values.applications }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: {{ $value.namespace | default $key}}
    name: {{ $value.namespace | default $key}}
  name: {{ $value.namespace | default $key}}
{{ end }}
