apiVersion: v2
name: geopulse
description: A self-hosted location tracking and analysis platform with PostGIS and optional MQTT support
type: application
version: 0.1.0
home: https://github.com/tess1o/geopulse
sources:
  - https://github.com/tess1o/geopulse
dependencies:
  - name: geopulse
    version: 1.30.0
    repository: https://tess1o.github.io/geopulse/charts
  - name: cluster
    version: 0.8.1
    repository: https://cloudnative-pg.github.io/charts
