geopulse:
  backend:
    image:
      repository: tess1o/geopulse-backend
      tag: "1.9.1-native-compat"

  postgres:
    enabled: false

  externalPostgres:
    host: "geopulse-cluster-rw"
    port: 5432
    database: app
    username: app
    password: ""

  keygen:
    
    persistence:
      enabled: true
      storageClass: "unraid-nfs-named"
      accessMode: ReadWriteOnce
      size: 10Mi

  # Application configuration
  config:
    uiUrl: "https://geopulse.robertclarke.co.uk"

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hostname: geopulse.robertclarke.co.uk
    tls:
      enabled: true
      secretName: geopulse-tls

  secrets:
    useExistingSecret: true
    existingSecretName: "geopulse-secrets"

cluster:
  cluster:
    instances: 1
    storage:
      storageClass: unraid-nfs-named
    initdb:
      secret:
        name:
  type: postgis
