httpRoute:
  enabled: true
  parentRefs:
    - name: http
      namespace: kgateway-system
      sectionName: https
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - geopulse.robertclarke.co.uk

geopulse:
  backend:
    image:
      repository: tess1o/geopulse-backend
      tag: "1.24.0-native-compat"

  postgres:
    enabled: false

  externalPostgres:
    host: "geopulse-cluster-rw"
    port: 5432
    database: app
    username: app
    password: ""

  keygen:
    
    persistence:
      enabled: true
      storageClass: "unraid-nfs-named"
      accessMode: ReadWriteOnce
      size: 10Mi

  # Application configuration
  config:
    uiUrl: "https://geopulse.robertclarke.co.uk"
    cookieDomain: ".robertclarke.co.uk"
    admin:
      email: "me@robertclarke.co.uk"
    auth:
      registrationEnabled: true

  secrets:
    useExistingSecret: true
    existingSecretName: "geopulse-secrets"

cluster:
  cluster:
    instances: 1
    storage:
      storageClass: unraid-nfs-named
    initdb:
      secret:
        name:
  type: postgis
