apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zennotes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: zennotes

  data:
    - secretKey: ZENNOTES_AUTH_TOKEN
      remoteRef:
        key: /zennotes/ZENNOTES_AUTH_TOKEN
