applicationHost: storyteller.robertclarke.co.uk

controllers:
  storyteller:
    enabled: true
    type: statefulset
    containers:
      storyteller:
        image:
          repository: registry.gitlab.com/storyteller-platform/storyteller
          tag: v2.11.12

        envFrom:
          - secretRef:
              name: "{{ .Release.Name }}"

    statefulset:
      volumeClaimTemplates:
        - name: data
          storageClass: unraid-nfs-named
          accessMode: ReadWriteOnce
          size: 10Gi
          globalMounts:
            - path: /data

secrets:
  storyteller:
    enabled: true
    stringData:
      STORYTELLER_SECRET_KEY: "{{ default (randAlphaNum 32) .Values.jsonWebToken }}"

service:
  storyteller:
    controller: storyteller
    ports:
      http:
        port: 8001

route:
  storyteller:
    enabled: true
    parentRefs:
      - name: http
        namespace: kgateway-system
        sectionName: https
        group: gateway.networking.k8s.io
        kind: Gateway
    hostnames:
      - "{{ .Values.applicationHost }}"

