apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: ghcr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "RobertClarke64",
                "password": "{{ .token }}",
                "auth": "{{ printf "RobertClarke64:%s" .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: token
      remoteRef:
        key: /personal-website/image-pull-token

