global:
  domain: argo.robertclarke.co.uk

argo-cd:
  server:
    ingress:
      enabled: true
      hostname: argo.robertclarke.co.uk
      ingressClassName: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  repoServer:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  dex:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  redis:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  applicationSet:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  notifications:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

dashboards:
  - name: "Operational / Overview"
    url: "https://grafana.com/grafana/dashboards/19993-argocd-operational-overview/"
