global:
  domain: argo.robertclarke.co.uk

argo-cd:
  server:
    ingress:
      enabled: true
      hostname: argo.robertclarke.co.uk
      ingressClassName: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        cert-manager.io/cluster-issuer: letsencrypt
      tls: true

    httproute:
      enabled: true
      parentRefs:
        - name: http
          namespace: kgateway-system
          sectionName: https
          group: gateway.networking.k8s.io
          kind: Gateway

    backendTLSPolicy:
      enabled: true
      targetRefs:
        - group: ""
          kind: Service
          name: argocd-server
          sectionName: https
      validation:
        caCertificateRefs:
          - kind: Secret
            group: ""
            name: argocd-server-tls
        hostname: argocd-server.argocd.svc.cluster.local

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  repoServer:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  dex:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  redis:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  applicationSet:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  notifications:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  configs:
    cm:
      resource.exclusions: |
        ### Network resources created by the Kubernetes control plane and excluded to reduce the number of watched events and UI clutter
        - apiGroups:
          - ''
          - discovery.k8s.io
          kinds:
          - Endpoints
          # - EndpointSlice # Using endpointslice for service proxying
        ### Internal Kubernetes resources excluded reduce the number of watched events
        - apiGroups:
          - coordination.k8s.io
          kinds:
          - Lease
        ### Internal Kubernetes Authz/Authn resources excluded reduce the number of watched events
        - apiGroups:
          - authentication.k8s.io
          - authorization.k8s.io
          kinds:
          - SelfSubjectReview
          - TokenReview
          - LocalSubjectAccessReview
          - SelfSubjectAccessReview
          - SelfSubjectRulesReview
          - SubjectAccessReview
        ### Intermediate Certificate Request excluded reduce the number of watched events
        - apiGroups:
          - certificates.k8s.io
          kinds:
          - CertificateSigningRequest
        - apiGroups:
          - cert-manager.io
          kinds:
          - CertificateRequest
        ### Cilium internal resources excluded reduce the number of watched events and UI Clutter
        - apiGroups:
          - cilium.io
          kinds:
          - CiliumIdentity
          - CiliumEndpoint
          - CiliumEndpointSlice
        ### Kyverno intermediate and reporting resources excluded reduce the number of watched events and improve performance
        - apiGroups:
          - kyverno.io
          - reports.kyverno.io
          - wgpolicyk8s.io
          kinds:
          - PolicyReport
          - ClusterPolicyReport
          - EphemeralReport
          - ClusterEphemeralReport
          - AdmissionReport
          - ClusterAdmissionReport
          - BackgroundScanReport
          - ClusterBackgroundScanReport
          - UpdateRequest

dashboards:
  argocd:
    url: "https://grafana.com/api/dashboards/14584/revisions/1/download"
  argocd-operational-overview:
    url: "https://grafana.com/api/dashboards/19993/revisions/4/download"
  argocd-notifications-overview:
    url: "https://grafana.com/api/dashboards/19975/revisions/4/download"
  argocd-application-overview:
    url: "https://grafana.com/api/dashboards/19974/revisions/4/download"
