global:
  domain: argo.robertclarke.co.uk

argo-cd:
  server:
    ingress:
      enabled: true
      hostname: argocd.robertclarke.co.uk
      ingressClassName: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
