apiVersion: v2
name: linkwarden
description: A Helm chart for Linkwarden
type: application
version: 0.1.0
dependencies:
  - name: linkwarden
    version: 1.0.1
    repository: https://soubenz.github.io/linkwarden-helm-chart/
