apiVersion: v2
name: linkwarden
description: A Helm chart for Linkwarden
type: application
version: 0.1.0
dependencies:
  - name: linkwarden
    version: 0.3.3
    repository: https://fmjstudios.github.io/helm
