global:
  security:
    allowInsecureImages: true

linkwarden:
  image:
    tag: v2.13.0

  linkwarden:
    domain: links.robertclarke.co.uk
    nextAuthSecret:
      existingSecret:
        name: linkwarden-auth
        key: token
    data:
      filesystem:
        pvc:
          size: 10Gi
          storageClass: unraid-nfs-named

  postgresql:
    image:
      repository: bitnamilegacy/postgresql

  ingress:
    enabled: true
    className: nginx
