global:
  security:
    allowInsecureImages: true

linkwarden:
  ingress:
    enabled: true
    className: nginx
  persistence:
    size: 10Gi
    storageClass: unraid-nfs

  postgresql:
    image:
      repository: bitnamilegacy/postgresql
