global:
  security:
    allowInsecureImages: true

linkwarden:
  ingress:
    enabled: true
    className: nginx
  data:
    filesystem:
      pvc:
        size: 10Gi
        storageClass: unraid-nfs

  postgresql:
    image:
      repository: bitnamilegacy/postgresql
