apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: karakeep-secrets

  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: /karakeep/NEXTAUTH_SECRET
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: /karakeep/MEILI_MASTER_KEY
