apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mybibliotheca
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: mybibliotheca

  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: /mybibliotheca/SECRET_KEY
    - secretKey: SECURITY_PASSWORD_SALT
      remoteRef:
        key: /mybibliotheca/SECURITY_PASSWORD_SALT
    - secretKey: GOOGLE_BOOKS_API_KEY
      remoteRef:
        key: /mybibliotheca/GOOGLE_BOOKS_API_KEY
