global: {}

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: false

httpRoute:
  enabled: true
  parentRefs:
    - name: http
      namespace: kgateway-system
      sectionName: https

server:
  hostname: "barassistant-server.robertclarke.co.uk"
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: barassistant/server
    pullPolicy: IfNotPresent
    tag: "5.13.2"

  env:
    - name: APP_URL
      value: "https://barassistant-server.robertclarke.co.uk"
    - name: MEILISEARCH_HOST
      value: "http://barassistant-search:7700"
    - name: MEILISEARCH_KEY
      valueFrom:
        secretKeyRef:
          name: barassistant-secrets
          key: MEILI_MASTER_KEY
    - name: CACHE_DRIVER
      value: "redis"
    - name: SESSION_DRIVER
      value: "redis"
    - name: REDIS_HOST
      value: "barassistant-redis"
    - name: ALLOW_REGISTRATION
      value: "true"
    - name: GEN_AI_PROVIDER
      value: "openai"
    - name: GEN_AI_MODEL
      value: gpt-4o
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: barassistant-secrets
          key: AI_API_KEY

  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    readOnlyRootFilesystem: false
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 8080

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  persistentVolume:
    create: true
    name: "server"
    storageClass: "unraid-nfs-named"
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi

  volumes:
    - name: server-data-pv
      persistentVolumeClaim:
        claimName: server

  volumeMounts:
    - name: server-data-pv
      mountPath: "/var/www/cocktails/storage/bar-assistant"

  nodeSelector: {}

  tolerations: []

  affinity: {}

search:
  hostname: "barassistant-search.robertclarke.co.uk"
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: getmeili/meilisearch
    pullPolicy: IfNotPresent
    tag: "v1.40.0"

  env:
    - name: MEILI_NO_ANALYTICS
      value: "true"
    - name: MEILI_ENV
      value: "production"
    - name: MEILI_MASTER_KEY
      valueFrom:
        secretKeyRef:
          name: barassistant-secrets
          key: MEILI_MASTER_KEY


  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 7700

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  persistentVolume:
    create: true
    name: "search"
    storageClass: "unraid-nfs-named"
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi

  volumes:
    - name: search-data-pv
      persistentVolumeClaim:
        claimName: search

  volumeMounts:
    - name: search-data-pv
      mountPath: "/meili_data"

  nodeSelector: {}

  tolerations: []

  affinity: {}

saltrim:
  hostname: "bar.robertclarke.co.uk"
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: barassistant/salt-rim
    pullPolicy: IfNotPresent
    tag: "4.14.1"

  env:
    - name: API_URL
      value: "https://barassistant-server.robertclarke.co.uk"
    - name: MEILISEARCH_URL
      value: "https://barassistant-search.robertclarke.co.uk"

  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 8080

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  persistentVolume:
    create: false

  volumes: []

  volumeMounts: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

redis:
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: "8.6.2"

  env:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"

  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 6379

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  persistentVolume:
    create: false

  volumes: []

  volumeMounts: []

  nodeSelector: {}

  tolerations: []

  affinity: {}
