apiVersion: v2
name: base
description: Helm chart for deploying metallb
type: application
version: 0.1.0
dependencies:
  - name: metallb
    version: 0.15.3
    repository: https://metallb.github.io/metallb
