matrix-stack:
  enabled: false
  serverName: robertclarke.co.uk

  synapse:
    ingress:
      host: matrix.robertclarke.co.uk
    postgres:
      host: matrix-stack-cluster-rw
      user: synapse
      database: synapse
      password:
        secret: matrix-cnpg-users
        secretKey: synapse
    media:
      storage:
        storageClassName: unraid-nfs-named
    appservices: []

  matrixAuthenticationService:
    ingress:
      host: mas.robertclarke.co.uk
    postgres:
      host: matrix-stack-cluster-rw
      user: mas
      database: mas
      password:
        secret: matrix-cnpg-users
        secretKey: mas

  matrixRTC:
    ingress:
      host: mrtc.robertclarke.co.uk

  elementWeb:
    ingress:
      host: chat.robertclarke.co.uk

  elementAdmin:
    ingress: 
      host: madmin.robertclarke.co.uk

  postgres:
    enabled: false

cluster:
  cluster:
    instances: 1
    storage:
      storageClass: unraid-nfs-named
    roles:
      - name: synapse
        login: true
        superuser: false
      - name: mas
        login: true
        superuser: false
  databases:
    - name: synapse
      owner: synapse
    - name: mas
      owner: mas
