matrix-stack:
  serverName: robertclarke.co.uk

  httpRoute:
    parentRefs:
      - name: http
        namespace: kgateway-system
        sectionName: https
        group: gateway.networking.k8s.io
        kind: Gateway

  synapse:
    ingress:
      enabled: false
      host: matrix.robertclarke.co.uk
    httpRoute:
      enabled: true
      hostnames:
        - matrix.robertclarke.co.uk
    postgres:
      host: matrix-stack-cluster-rw
      user: synapse
      database: synapse
      password:
        secret: matrix-cnpg-synapse
        secretKey: password
    media:
      storage:
        storageClassName: unraid-nfs-named
    appservices:
      - secret: matrix-appservices
        secretKey: discord

  matrixAuthenticationService:
    ingress:
      enabled: false
      host: mas.robertclarke.co.uk
    httpRoute:
      enabled: true
      hostnames:
        - mas.robertclarke.co.uk
    postgres:
      host: matrix-stack-cluster-rw
      user: mas
      database: mas
      password:
        secret: matrix-cnpg-mas
        secretKey: password
    additional:
      email-config.yaml:
        configSecret: matrix-email
        configSecretKey: emailConfig
      user-config.yaml:
        config: |
          account:
            password_registration_enabled: true
            password_recovery_enabled: true
            account_deactivation_allowed: true
            login_with_email_allowed: true

  matrixRTC:
    ingress:
      enabled: false
      host: mrtc.robertclarke.co.uk
    httpRoute:
      enabled: true
      hostnames:
        - mrtc.robertclarke.co.uk

  elementWeb:
    ingress:
      enabled: false
      host: chat.robertclarke.co.uk
    httpRoute:
      enabled: true
      hostnames:
        - chat.robertclarke.co.uk

  elementAdmin:
    ingress: 
      enabled: false
      host: madmin.robertclarke.co.uk
    httpRoute:
      enabled: true
      hostnames:
        - madmin.robertclarke.co.uk


  ingress:
    annotations:
      argocd.argoproj.io/ignore-resource-updates: "true"

  wellKnownDelegation:
    enabled: true
    ingress:
      enabled: false
    httpRoute:
      enabled: true
      hostnames:
        - well-known.robertclarke.co.uk

  postgres:
    enabled: false

cluster:
  cluster:
    instances: 1
    storage:
      storageClass: unraid-nfs-named
    roles:
      - name: synapse
        login: true
        superuser: false
        passwordSecret:
          name: matrix-cnpg-synapse
      - name: mas
        login: true
        superuser: false
        passwordSecret:
          name: matrix-cnpg-mas
  databases:
    - name: synapse
      owner: synapse
    - name: mas
      owner: mas
