route:
  app:
    enabled: true
    parentRefs:
      - name: http
        namespace: kgateway-system
        group: gateway.networking.k8s.io
        kind: Gateway
    hostnames:
      - journiv.robertclarke.co.uk

controllers:
  celery-worker:
    type: deployment
    strategy: Recreate
    containers:
      celery-worker:
        image:
          repository: swalabtech/journiv-app
          tag: 0.1.0-beta.8
          pullPolicy: IfNotPresent
        command: ["celery", "-A", "app.core.celery_app", "worker", "--loglevel=info"]
        env:
          ENVIRONMENT: production
          DOMAIN_NAME: journiv.robertclarke.co.uk
          REDIS_URL: redis://journiv-valkey:6379/0
          CELERY_BROKER_URL: redis://journiv-valkey:6379/0
          CELERY_RESULT_BACKEND: redis://journiv-valkey:6379/0
          SECRET_KEY:
            valueFrom:
              secretKeyRef:
                name: journiv
                key: SECRET_KEY

  app:
    type: deployment
    strategy: Recreate
    containers:
      app:
        image:
          repository: swalabtech/journiv-app
          tag: 0.1.0-beta.8
          pullPolicy: IfNotPresent
        env:
          ENVIRONMENT: production
          DOMAIN_NAME: journiv.robertclarke.co.uk
          REDIS_URL: redis://journiv-valkey:6379/0
          CELERY_BROKER_URL: redis://journiv-valkey:6379/0
          CELERY_RESULT_BACKEND: redis://journiv-valkey:6379/0
          RATE_LIMIT_STORAGE_URI: redis://journiv-valkey:6379/1
          SECRET_KEY:
            valueFrom:
              secretKeyRef:
                name: journiv
                key: SECRET_KEY

service:
  app:
    controller: app
    ports:
      http:
        port: 8000

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: unraid-nfs-named
