controllers:
  celery-worker:
    type: deployment
    strategy: Recreate
    containers:
      celery-worker:
        image:
          repository: swalabtech/journiv-app
          tag: 0.1.0-beta.8
          pullPolicy: IfNotPresent
        command: ["celery", "-A", "app.core.celery_app", "worker", "--loglevel=info"]
        env:
          ENVIRONMENT: production
          DOMAIN_NAME: journiv.robertclarke.co.uk
          REDIS_URL: redis://journiv-valkey:6379/0
          CELERY_BROKER_URL: redis://journiv-valkey:6379/0
          CELERY_RESULT_BACKEND: redis://journiv-valkey:6379/0
          SECRET_KEY:
            valueFrom:
              secretKeyRef:
                name: journiv
                key: SECRET_KEY
        volumes:
          - name: app-data
            mountPath: /data

  app:
    type: deployment
    strategy: Recreate
    containers:
      app:
        image:
          repository: swalabtech/journiv-app
          tag: 0.1.0-beta.8
          pullPolicy: IfNotPresent
        env:
          ENVIRONMENT: production
          DOMAIN_NAME: journiv.robertclarke.co.uk
          REDIS_URL: redis://journiv-valkey:6379/0
          CELERY_BROKER_URL: redis://journiv-valkey:6379/0
          CELERY_RESULT_BACKEND: redis://journiv-valkey:6379/0
          RATE_LIMIT_STORAGE_URI: redis://journiv-valkey:6379/1
          SECRET_KEY:
            valueFrom:
              secretKeyRef:
                name: journiv
                key: SECRET_KEY
        volumes:
          - name: app-data
            mountPath: /data

service:
  app:
    controller: app
    ports:
      http:
        port: 8000

ingress:
  app:
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: journiv.robertclarke.co.uk
        paths:
          - path: /
            pathType: ImplementationSpecific
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - journiv.robertclarke.co.uk
        secretName: journiv-tls

persistence:
  app-data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: unraid-nfs-named
