apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-sample
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: 6adb342c-c144-4d35-a576-922b8a6973de
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
          projectSlug: home-kubernetes-f-zg9
          envSlug: prod
          secretsPath: "/test-secrets"
          recursive: true
  managedKubeSecretReferences:
    - secretName: test-secrets
      secretNamespace: infisical
      creationPolicy: "Orphan"