kite:
  host: https://kite.robertclarke.co.uk

  db:
    sqlite:
      persistence:
        pvc:
          enabled: true
          storageClass: unraid-nfs-named

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: kite.robertclarke.co.uk
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - kite.robertclarke.co.uk
        secretName: kite-tls
