apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-cnpg-users
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: matrix-cnpg-users

  data:
    - secretKey: synapse
      remoteRef:
        key: /matrix/postgres/synapseUserPassword
    - secretKey: mas
      remoteRef:
        key: /matrix/postgres/masUserPassword
