apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-cnpg-synapse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: matrix-cnpg-synapse

  data:
    - secretKey: username
      remoteRef:
        key: /matrix-stack/postgres/synapse/username
    - secretKey: password
      remoteRef:
        key: /matrix-stack/postgres/synapse/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-cnpg-mas
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: matrix-cnpg-mas

  data:
    - secretKey: username
      remoteRef:
        key: /matrix-stack/postgres/mas/username
    - secretKey: password
      remoteRef:
        key: /matrix-stack/postgres/mas/password
