apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: barassistant-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: barassistant-secrets

  data:
    - secretKey: AI_API_KEY
      remoteRef:
        key: /barassistant/AI_API_KEY
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: /barassistant/MEILI_MASTER_KEY
    - secretKey: MEILISEARCH_API_KEY_UID
      remoteRef:
        key: /barassistant/MEILISEARCH_API_KEY_UID
