httpRoute:
  enabled: true
  parentRefs:
    - name: http
      namespace: kgateway-system
      sectionName: https
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - pdf.robertclarke.co.uk

stirling-pdf:
  image:
    repository: stirlingtools/stirling-pdf
    tag: "2.6.0"
  probes:
    liveness:
      initialDelaySeconds: 60
  deployment:
    extraVolumeMounts:
      - name: storage-volume
        mountPath: /configs
  persistence:
    enabled: true
    storageClass: "unraid-nfs-named"
    path: "/configs"
