
clickstack:
  # hyperdx:
  #   config:
  #     FRONTEND_URL: "https://hyperdx.robertclarke.co.uk"

  clickhouse:
    cluster:
      spec:
        podTemplate:
          securityContext:
            fsGroup: 101
            fsGroupChangePolicy: OnRootMismatch
            runAsUser: 101
            runAsGroup: 101
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
