apiVersion: v2
name: karakeep
description: A Helm Chart for deploying karakeep
type: application
version: 0.1.0
dependencies:
  - name: karakeep
    version: 0.31.0
    repository: https://karakeep-app.github.io/helm-charts
