karakeep:
  applicationHost: keep.robertclarke.co.uk
  ingress:
    karakeep:
      className: nginx

  secrets:
    meilesearch:
      enabled: false
    karakeep:
      enabled: false

  controllers:
    karakeep:
      containers:
        karakeep:
          env:
            CRAWLER_VIDEO_DOWNLOAD: true
