apiVersion: v2
name: trek
description: A Helm Chart for deploying Trek
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
