apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monica
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: monica

  data:
    - secretKey: emailUsername
      remoteRef:
        key: /monica/emailUsername
    - secretKey: emailPassword
      remoteRef:
        key: /monica/emailPassword
    - secretKey: appKey
      remoteRef:
        key: /monica/appKey
