apiVersion: v2
name: convertx
description: A Helm Chart for deploying ConvertX
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/
