applicationHost: convert.robertclarke.co.uk

controllers:
  convertx:
    enabled: true
    type: statefulset
    containers:
      convertx:
        image:
          repository: ghcr.io/c4illin/convertx
          tag: v0.18.0

        envFrom:
          - secretRef:
              name: "{{ .Release.Name }}"

    statefulset:
      volumeClaimTemplates:
        - name: data
          storageClass: unraid-nfs-named
          accessMode: ReadWriteOnce
          size: 10Gi
          globalMounts:
            - path: /app/data

secrets:
  convertx:
    enabled: true
    stringData:
      JWT_SECRET: "{{ default (randAlphaNum 48) .Values.jsonWebToken }}"

service:
  convertx:
    controller: convertx
    ports:
      http:
        port: 3000

route:
  convertx:
    enabled: true
    parentRefs:
      - name: http
        namespace: kgateway-system
        sectionName: https
        group: gateway.networking.k8s.io
        kind: Gateway
    hostnames:
      - "{{ .Values.applicationHost }}"

