apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgvecto-rs.fullname" . }}-pgvectors
  labels:
    {{- include "pgvecto-rs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pgvecto-rs.selectorLabels" . | nindent 4 }}
