firefly-iii-stack:
  firefly-db:
    storage:
      class: unraid-nfs
      accessModes: ReadWriteOnce
    backup:
      pvc:
        class: unraid-nfs

  firefly-iii:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - firefly.robertclarke.co.uk
      annotations:
        nginx.org/redirect-to-https: "true"
    config:
      existingSecret: firefly-iii
      env:
        APP_URL: https://firefly.robertclarke.co.uk
        TRUSTED_PROXIES: "*"

  importer:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - importer.firefly.robertclarke.co.uk
