firefly-iii-stack:
  firefly-db:
    storage:
      class: unraid-nfs-named
      accessModes: ReadWriteOnce
    backup:
      pvc:
        class: unraid-nfs-named

  firefly-iii:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - firefly.robertclarke.co.uk
      tls:
        - hosts:
            - firefly.robertclarke.co.uk
          secretName: firefly-iii-tls
    config:
      existingSecret: firefly-iii
      env:
        APP_URL: https://firefly.robertclarke.co.uk
        TRUSTED_PROXIES: "*"
    persistence:
      storageClassName: unraid-nfs-named

  importer:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - importer.firefly.robertclarke.co.uk
      tls:
        - hosts:
            - importer.firefly.robertclarke.co.uk
          secretName: firefly-iii-importer-tls
    fireflyiii:
      url: http://firefly-iii:80
      vanityUrl: https://firefly.robertclarke.co.uk
    config:
      existingSecret: firefly-iii-importer-env
