firefly-iii-stack:
  firefly-db:
    storage:
      class: unraid-nfs
      accessModes: ReadWriteOnce
    backup:
      pvc:
        class: unraid-nfs

  firefly-iii:
    enabled: true
    ingress:
      className: nginx
      hosts:
        firefly.robertclarke.co.uk

  importer:
    enabled: true
    ingress:
      className: nginx
      hosts:
        importer.firefly.robertclarke.co.uk
