# Default values for wanderer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  env:
    - name: MEILI_URL
      value: "http://wanderer-search:7700"
    - name: MEILI_MASTER_KEY
      valueFrom:
        secretKeyRef:
          name: wanderer-search-master-key
          key: MEILI_MASTER_KEY

search:
  image:
    repository: getmeili/meilisearch
    pullPolicy: IfNotPresent
    tag: "v1.24.0"
  imagePullSecrets: []
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  service:
    type: ClusterIP
    port: 7700
  livenessProbe:
    httpGet:
      path: /health
      port: http
  readinessProbe:
    httpGet:
      path: /health
      port: http
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # Additional volumes on the output Deployment definition.
  volumes:
    - name: meili-data-pv
      persistentVolumeClaim:
        claimName: search
  volumeMounts:
    - name: meili-data-pv
      mountPath: "/meili_data/data.ms"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  env:
    - name: MEILI_NO_ANALYTICS
      value: "true"
  args:
    - "/bin/sh"
    - "-c"
    - "/bin/meilisearch --experimental-dumpless-upgrade"
  persistentVolume:
    create: true
    name: "search"
    storageClass: "unraid-nfs-named"
    accessModes:
      - ReadWriteOncePod
    resources:
      requests:
        storage: 10Gi

db:
  image:
    repository: flomp/wanderer-db
    pullPolicy: IfNotPresent
    tag: "v0.18.3"
  imagePullSecrets: []
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  service:
    type: ClusterIP
    port: 8090
  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # Additional volumes on the output Deployment definition.
  volumes:
    - name: db-data-pv
      persistentVolumeClaim:
        claimName: db
  volumeMounts:
    - name: db-data-pv
      mountPath: "/pb_data"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  persistentVolume:
    create: true
    name: "db"
    storageClass: "unraid-nfs-named"
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
  env:
    - name: POCKETBASE_ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          name: wanderer-search-master-key
          key: POCKETBASE_ENCRYPTION_KEY
    - name: POCKETBASE_CRON_SYNC_SCHEDULE
      value: "*/30 * * * *"
    - name: POCKETBASE_SMTP_ENABLED
      value: "true"
    - name: POCKETBASE_SMTP_HOST
      value: "robertclarke.co.uk"
    - name: POCKETBASE_SMTP_PORT
      value: "465"
    - name: POCKETBASE_SMTP_USERNAME
      value: "wanderer@robertclarke.co.uk"
    - name: POCKETBASE_SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: wanderer-search-master-key
          key: POCKETBASE_SMTP_PASSWORD
    - name: POCKETBASE_SMTP_SENDER_ADDRESS
      value: "wanderer@robertclarke.co.uk"
    - name: POCKETBASE_SMTP_SENDER_NAME
      value: "Wanderer"
    - name: ORIGIN
      value: https://wanderer.robertclarke.co.uk

web:
  image:
    # repository: flomp/wanderer-web
    repository: robertclarke64/wanderer-web
    pullPolicy: IfNotPresent
    tag: "v0.18.3-print-waypoints"
  imagePullSecrets: []
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  service:
    type: ClusterIP
    port: 3000
  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # Additional volumes on the output Deployment definition.
  volumes:
    - name: web-data-pv
      persistentVolumeClaim:
        claimName: web
  volumeMounts:
    - name: web-data-pv
      mountPath: "/app/uploads"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  env:
    - name: ORIGIN
      value: https://wanderer.robertclarke.co.uk
    - name: BODY_SIZE_LIMIT
      value: Infinity
    - name: PUBLIC_POCKETBASE_URL
      value: http://wanderer-db:8090
    - name: PUBLIC_DISABLE_SIGNUP
      value: "false"
    - name: UPLOAD_FOLDER
      value: /app/uploads
    - name: UPLOAD_USER
      value: admin
    - name: UPLOAD_PASSWORD
      value: admin
    - name: PUBLIC_OVERPASS_API_URL
      value: https://overpass-api.de
    - name: PUBLIC_VALHALLA_URL
      value: https://valhalla1.openstreetmap.de
    - name: PUBLIC_NOMINATIM_URL
      value: https://nominatim.openstreetmap.org
  persistentVolume:
    create: true
    name: "web"
    storageClass: "unraid-nfs-named"
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: wanderer.robertclarke.co.uk
      paths:
        - path: /_
          pathType: Prefix
          service: wanderer-db
          port: 8090
        - path: /
          pathType: Prefix
          service: wanderer-web
          port: 3000
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
