apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "mautrix-bridge.fullname" . }}-registration
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: 10s

  target:
    name: mautrix-discord-registration

  data:
    - secretKey: registration.yaml
      remoteRef:
        key: /matrix-bridges/mautrix-discord-registration
