monica:
  monica:
    host: people.robertclarke.co.uk
    extraEnv:
      - name: APP_URL
        value: "https://people.robertclarke.co.uk"
      - name: APP_TRUSTED_PROXIES
        value: "*"
    existingSecret:
      enabled: true
      secretName: monica
      mailUsernameKey: emailUsername
      mailPasswordKey: emailPassword
    mail:
      enabled: true
      fromAddress: monica@robertclarke.co.uk
      replyToAddress: monica@robertclarke.co.uk
      smtp:
        host: robertclarke.co.uk
        encryption: tls
        port: 587

  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - hosts:
          - people.robertclarke.co.uk
        secretName: monica-tls

  persistence:
    enabled: true
    storageClassName: unraid-nfs

  internalDatabase:
    enabled: false

  externalDatabase:
    type: postgresql
    host: monica-cluster-rw
    database: app
    existingSecret:
      enabled: true
      secretName: monica-cluster-app
      usernameKey: username
      passwordKey: password

cluster:
  cluster:
    instances: 1
