monica:
  monica:
    host: people.robertclarke.co.uk
    extraEnv:
      - name: APP_URL
        value: "https://people.robertclarke.co.uk"
      - name: APP_TRUSTED_PROXIES
        value: "*"

  ingress:
    enabled: true
    className: nginx

  persistence:
    enabled: true
    storageClassName: unraid-nfs
