apiVersion: v2
name: cert-manager
description: A Helm Chart for deploying cert-manager
type: application
version: 0.1.0
dependencies:
  - name: cert-manager
    version: v1.21.0
    repository: oci://quay.io/jetstack/charts
