kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http
  namespace: kgateway-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: kgateway
  listeners:
  - name: https-root-domain
    protocol: HTTPS
    hostname: "robertclarke.co.uk"
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - name: robertclarke-root-co-uk-tls
          group: ''
          kind: Secret
  - protocol: HTTPS
    hostname: "*.robertclarke.co.uk"
    port: 443
    name: https
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - name: robertclarke-co-uk-tls
          group: ''
          kind: Secret
  - protocol: HTTP
    hostname: "*.robertclarke.co.uk"
    port: 80
    name: http
    allowedRoutes:
      namespaces:
        from: All
  addresses:
    - type: IPAddress
      value: 192.168.1.244
