apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: thinkcentre-tls-policy
spec:
  targetRefs:
    - kind: Service
      name: thinkcentre
      group: ""
  validation:
    caCertificateRefs:
      - kind: ConfigMap
        name: thinkcentre-ca
        group: ""
    hostname: "thinkcentre.localdomain"

