{{- range $service := .Values.proxy.services }}
{{- if ($service.tlsPolicy).enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ $service.name }}-tls-policy
spec:
  targetRefs:
    - kind: Service
      name: {{ $service.name }}
      group: ""
  validation:
    caCertificateRefs:
      - kind: ConfigMap
        name: {{ $service.name }}-ca
        group: ""
    hostname: {{ $service.tlsPolicy.caHost }}
{{- end }}
{{- end }}
