# CA Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-ca
data:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIFPzCCBCegAwIBAgISBQ93fQuF2dTmrs4JaFs7quEpMA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    EwNSMTMwHhcNMjYwMTIwMTEyOTA2WhcNMjYwNDIwMTEyOTA1WjA5MTcwNQYDVQQD
    DC4qLjk0NzBlZGJjMzFhZjRjN2NhZDcxOTliYThlMzY0ZTgyLnBsZXguZGlyZWN0
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0lSmhHFni3omC98CmNCD
    FDDeRSG5sAdaKQaVOLA26AoNJE6ChoAyE8moKenAjIy60Sz9Tv9fTyR/mkZv1m+T
    XZz+tPsUu4tJlmc0+pFXDxE98v4I+LBPM1cY/apjNVSl8K6aJvLwNn+v/UY/bYee
    BmPcdSmhRKR1naFoiuhT62EX9Qhvszf9xe0wqevQTB5NsY0v0/ZXGWFFE95BtCjd
    4grbQv5iB3bPavyB/doSQJFgttuFjdckyRJZT2I0zyYrv8VRMnY34SOy2j1XB5TV
    9ZP/y+ZmvGffHbSZ6eofDODk5VCW9A8GQfrynG1b6GcILmZIcjnnmDSV/tTPEvNH
    dwIDAQABo4ICRTCCAkEwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUF
    BwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQenwDxNzlAk5tY
    YaoB1cpPfGhT7zAfBgNVHSMEGDAWgBTnq58PLDOgU9NeT3jIsoQOO9aSMzAzBggr
    BgEFBQcBAQQnMCUwIwYIKwYBBQUHMAKGF2h0dHA6Ly9yMTMuaS5sZW5jci5vcmcv
    MDkGA1UdEQQyMDCCLiouOTQ3MGVkYmMzMWFmNGM3Y2FkNzE5OWJhOGUzNjRlODIu
    cGxleC5kaXJlY3QwEwYDVR0gBAwwCjAIBgZngQwBAgEwLgYDVR0fBCcwJTAjoCGg
    H4YdaHR0cDovL3IxMy5jLmxlbmNyLm9yZy80Mi5jcmwwggELBgorBgEEAdZ5AgQC
    BIH8BIH5APcAfQAai51pSleYyJmgyoi99I/AtFZgzMNgDR9x9Gn/x9GsowAAAZvb
    X/WMAAgAAAUAOhUk/wQDAEYwRAIgQICo2g0gvgannsjBmPAMFWTjmUxPoRvzSon1
    /u3rMw4CIDVKYV8WY4YOCs6Hx22IAljL1ZKvYqcLr9ROrYz1l3naAHYASZybad4d
    fOz8Nt7Nh2SmuFuvCoeAGdFVUvvp6ynd+MMAAAGb21/6NAAABAMARzBFAiBVuVEY
    Nkh8d3fYUaknFusuBzK3zGn4Iqv63tX+uFq39wIhAKOds4ZCQ/BG5Oa/bdyJgXjj
    BA/67Xi6LAcJZVDsjob2MA0GCSqGSIb3DQEBCwUAA4IBAQBx2eaAQTMu3sNzyHjI
    hezqvhiRcHnI1WmKpli1Xq4gtnIxR135FLN83wXdKKCOZIH5VupaMoWmypIwsAoa
    R2L1haO6l2Nnt+HiYfvzytUDIfdV4pQO2inPvbT/PrUuDVS45o6F+R8Ac0pzEiJ7
    VjDf/8PYxcP9bD3uzW43/AewHH1hvceHKW5ymuzuUZx0EP8lI47ljtx1fXlkqM6Y
    Se14OOjuvAcBg7Nu6KUMc+uqKWkSdocRNyxp9U6Qbl3hHgvNaLjjQXb/3jWZHm8a
    MP95SYg6Sgri2t+l6V5Wj7UYaJACMIPt6Vx4RMZupmSE3JX5Cv2j3usBlFiGTOr9
    IFul
    -----END CERTIFICATE-----
