{{- range $service := .Values.proxy.services }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ $service.name }}
  labels:
    kubernetes.io/service-name: {{ $service.name }}
addressType: IPv4
ports:
  - port: {{ $service.port }}
endpoints:
  - addresses:
      - {{ default $.Values.proxy.ipAddress $service.ipAddress }}
    conditions: {}
{{- end }}
