name: CI Pipeline
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
jobs:
  git-diff:
    name: Git diff Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.git-diff.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Get list of changed directories
        id: git-diff
        run: |
          changed=$(git diff --name-only HEAD^..HEAD | cut -d/ -f1 | uniq | jq -R . | jq -cs .)
          echo $changed
          echo "changed=$changed" >> $GITHUB_OUTPUT

      - name: Output changed directories
        run: |
          echo "Changed directories: ${{ steps.git-diff.outputs.changed }}"
  
  helm-diff:
    name: Helm Diff Changes
    runs-on: ubuntu-latest
    needs: git-diff
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.git-diff.outputs.changed) }}
        exclude:
          - chart: ".github"
          - chart: ".gitignore"
          - chart: ".renovate.json"
          - chart: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Helm Diff
        uses: ./.github/actions/helm-diff
        with:
          helm-chart: ${{ matrix.chart }}
