name: 'Helm Diff'
description: 'Diff Helm chart changes'
inputs:
  helm-chart:
    description: 'Helm chart to diff'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Helm
      uses: azure/setup-helm@v4
      id: install-helm

    - name: Template new chart
      id: template-new
      shell: bash
      run: |
        cat << EOF > repositories.yaml
        apiVersion: ""
        generated: "0001-01-01T00:00:00Z"
        repositories:
        EOF
        cat ${{ inputs.helm-chart }}/Chart.lock | yq '[.dependencies[] | select(.repository!="oci://*") ] | map_values(.caFile="", .certFile="", .insecure_skip_tls_verify=false, .keyFile="", .pass_credentials_all=false, .password="", .url=.repository, .username="") | del(.[].repository)' >> repositories.yaml
        helm dependency update ./${{ inputs.helm-chart }} --repository-config repositories.yaml
        helm template ${{ inputs.helm-chart }} ./${{ inputs.helm-chart }} > new-chart.yaml

    - name: Template old chart
      id: template-old
      shell: bash
      run: |
        git checkout HEAD^ -- ./${{ inputs.helm-chart }}
        cat << EOF > repositories.yaml
        apiVersion: ""
        generated: "0001-01-01T00:00:00Z"
        repositories:
        EOF
        cat ${{ inputs.helm-chart }}/Chart.lock | yq '.dependencies | map_values(.caFile="", .certFile="", .insecure_skip_tls_verify=false, .keyFile="", .pass_credentials_all=false, .password="", .url=.repository, .username="") | del(.[].repository)' >> repositories.yaml
        helm dependency update ./${{ inputs.helm-chart }} --repository-config repositories.yaml
        helm template ${{ inputs.helm-chart }} ./${{ inputs.helm-chart }} > old-chart.yaml
        git reset --hard

    - name: Diff charts
      id: diff
      shell: bash
      run: |
        diff_output=$(diff -u old-chart.yaml new-chart.yaml || true)
        echo "$diff_output"
        echo "diff=$diff_output" >> $GITHUB_OUTPUT

