name: 'Helm Diff'
description: 'Diff Helm chart changes'
inputs:
  helm-chart:
    description: 'Helm chart to diff'
    required: true
runs:
  using: "composite"
  steps:
    - name: Template new chart
      uses: ./.github/actions/helm-template
      with:
        helm-chart: ${{ matrix.chart }}
        output-file: new-chart.yaml

    - name: Switch to old commit
      shell: bash
      run: git checkout HEAD^ -- ./${{ inputs.helm-chart }}

    - name: Template old chart
      uses: ./.github/actions/helm-template
      with:
        helm-chart: ${{ matrix.chart }}
        output-file: old-chart.yaml

    - name: git reset --hard
      shell: bash
      run: git reset --hard

    - name: Diff charts
      id: diff
      shell: bash
      run: |
        diff_output=$(diff -u old-chart.yaml new-chart.yaml || true)
        echo "$diff_output"
        echo "diff=$diff_output" >> $GITHUB_OUTPUT

